### ISSUE TITLE
Service 및 Validate 작성

### ISSUE THREAD

**Issue by ffinn92** [ffinn92/MUSINSA_Assignment#5]
## 💡 issue
컨트롤러에 필요한 서비스 기능과 파라미터 유효성 검사를 구현한다.

## 📝 todo
- [x] 전체 카테고리 조회 서비스 구현
- [x] 상위 카테고리로 하위 카테고리 조회 서비스 구현
- [x] 카테고리 등록 서비스 구현
- [x] 카테고리 수정 서비스 구현
- [x] 카테고리 삭제 서비스 구현
- [x] 전체 카테고리 리스트 유효성 검사 메소드 구현
- [x] Id로 체크하는 특정 카테고리 유효성 검사 메소드 구현
- [x] Name으로 체크하는 특정 카테고리 유효성 검사 메소드 구현
